-- EMS-tydares-central / 02-data-ingest
-- ORDS endpoint scaffold: /ingest/data
-- Placeholder for ORDS module + handler.

-- Headers:
-- - X-Site-Id
-- - X-Edge-Id
-- - X-Idempotency-Key
--
-- Body (minimum):
-- {
--   "ts": "2026-01-07T05:12:34+08:00",
--   "type": "meter_reading",
--   "device_id": "gateway-01",
--   "payload": { ... }
-- }
--
-- ACK:
-- { ok, status: stored|duplicate|rejected, idempotency_key, server_time, ... }
